list.students:
    path: /
    controller: App\Controller\Admin\StudentsController::index

add.students:
    path: /add
    controller: App\Controller\Admin\StudentsController:add

edit.students:
    path: /edit/{id}
    controller: App\Controller\Admin\StudentsController:edit
